#! /bin/sh
SERVER_IP=$1
mc database/database-ui
m1 database/database-warehouse
scp -i ~/.ssh/q.pem /c/WS/5.2/server/database/database-ui/target/ttt-uidb-cli.jar root@$SERVER_IP:/opt/ttt/lib
scp -i ~/.ssh/q.pem /c/WS/5.2/server/database/database-warehouse/target/ttt-whdb-cli.jar root@$SERVER_IP:/opt/ttt/lib
ssh -o StrictHostKeyChecking=no -i /d/q.pem root@$SERVER_IP "rm -rf /tmp/*.sql; cd /tmp; java -jar -DSETTINGS=/opt/ttt/zlabmq.settings /opt/ttt/lib/ttt-uidb-cli.jar -s ttt \"\" postgres_upgrade_global_x.sql postgres_upgrade_customer_x.sql postgres_add_customer_x.sql; java -jar -DSETTINGS=/opt/ttt/zlabmq.settings /opt/ttt/lib/ttt-whdb-cli.jar -s ttt \"\" vertica_upgrade_global_x.sql vertica_upgrade_customer_x.sql vertica_add_customer_x.sql"
scp -i ~/.ssh/q.pem root@$SERVER_IP:/tmp/*.sql /d/

