#! /bin/sh
SERVER_IP=$1
m1 database/database-ui
scp -i ~/.ssh/q.pem /c/WS/5.2/server/database/database-ui/target/ttt-uidb-cli.jar root@$SERVER_IP:/opt/ttt/lib
ssh -o StrictHostKeyChecking=no -i /d/q.pem root@$SERVER_IP "rm -rf /tmp/*_x.sql; cd /tmp; java -jar -DSETTINGS=/opt/ttt/zlabmq.settings /opt/ttt/lib/ttt-uidb-cli.jar -s ttt \"\" postgres_upgrade_global_x.sql postgres_upgrade_customer_x.sql postgres_add_customer_x.sql"
scp -i ~/.ssh/q.pem root@$SERVER_IP:/tmp/*_x.sql /d/

