#! /bin/sh
logfile="$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $2@$1 'ls -1tr /var/log/ttt.log-* | tail -n 1')"
echo "logfile $logfile"
ssh -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $2@$1 "\
sudo rm -rf /tmp/zzz_x.gz; \
sudo cp $logfile /tmp/zzz_x.gz; \
sudo chown $2:$2 /tmp/zzz_x.gz"
scp -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $2@$1:/tmp/zzz_x.gz /d/
echo "unzipping"
gzip -d -c /d/zzz_x.gz > /d/tmp/ttt.log
echo "removing metrics"
time grep -v -e ".*metrics - type=.*" -e ".*metrics-logger.*" -e ".*\.HealthMonitor.*" -e ".*NoSqlSession.*" /d/tmp/ttt.log > /d/tmp/ttt_$1.log;
echo 'trimming exeptions';
time sed -i "/.* #011at/ s//\t#at/g" /d/tmp/ttt_$1.log;
rm -rvf /d/tmp/ttt.log