#! /bin/sh
logfile="/tmp/zzz_${1}_$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $2@$1 hostname).log"
ssh -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $2@$1 "\
sudo rm -rf /tmp/zzz_x.tar.gz; \
sudo cp /var/log/ttt.log $logfile; \
echo 'archiving log'; \
sudo tar cvfz /tmp/zzz_x.tar.gz $logfile; \
sudo rm -rf $logfile; \
sudo chown $2:$2 /tmp/zzz_x.tar.gz"
scp -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $2@$1:/tmp/zzz_x.tar.gz /d/
tar -xzvf /d/zzz_x.tar.gz -C /d/