#! /bin/sh
ZIFTEN_HOST="dev-single"$1
ssh -i /d/q.pem root@jenkins "\
echo \"Revering instance $ZIFTEN_HOST to base ... \" ; \
salt-cloud -a revert_to_snapshot $ZIFTEN_HOST snapshot_name=\"base\" -y ; \
sleep 5 ; \
echo \"Starting instance $ZIFTEN_HOST ... \" ; \
salt-cloud -a start $ZIFTEN_HOST -y; \
sleep 60; \
salt $ZIFTEN_HOST cmd.run \"rm -rvf /root/.inuse\""