#! /bin/sh
USER_NAME="$2"
if [ -z "$USER_NAME" ]; then
  USER_NAME="centos"
fi
echo "User name $USER_NAME"
logfile="/tmp/z_${1}_$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $USER_NAME@$1 hostname).log"
day=$(date +%-d)
month=$(date +%-b)
echo "Selecting today's log, $month $day"
ssh -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $USER_NAME@$1 "\
sudo rm -rf /tmp/z_x.tar.gz; \
echo 'removing metric lines && copy to temp'; \
time sudo grep -A 100000000 -E \"^$month [ ]?$day \" /var/log/ttt.log | grep -v -e \".*metrics - type=.*\" -e \".*metrics-logger.*\" -e \".*\.NoSqlSession.*\"  > $logfile; \
echo ; \
echo 'archiving log'; \
sudo tar cvfz /tmp/z_x.tar.gz $logfile; \
sudo rm -rf $logfile; \
sudo chown $2:$2 /tmp/z_x.tar.gz"
scp -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $USER_NAME@$1:/tmp/z_x.tar.gz /d/
tar -xzvf /d/z_x.tar.gz -C /d/