#! /bin/sh
logfile="/tmp/zzz_${1}_$(ssh -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $2@$1 hostname).log"
ssh -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $2@$1 "\
sudo rm -rf /tmp/zzz_x.tar.gz; \
echo 'removing metric lines && copy to temp'; \
time sudo grep -v -e \".*metrics - type=.*\" -e \".*metrics-logger.*\" -e \".*\.HealthMonitor.*\" -e \".*\.NoSqlSession.*\" /var/log/ttt.log > $logfile; \
echo ; \
echo 'trimming exeptions'; \
time sed -i \"/.* #011at/ s//\t#at/g\" $logfile; \
echo ; \
echo 'archiving log'; \
sudo tar cvfz /tmp/zzz_x.tar.gz $logfile; \
sudo rm -rf $logfile; \
sudo chown $2:$2 /tmp/zzz_x.tar.gz"
scp -o StrictHostKeyChecking=no -i ~/.ssh/c.pem $2@$1:/tmp/zzz_x.tar.gz /d/
tar -xzvf /d/zzz_x.tar.gz -C /d/
today=$(date +%-d)
echo "Selecting today's log, day: $today"
grep -A 1000000000 "$today 00:" /d/$logfile > /d/tmp/_today_$1.log