#! /bin/sh
cd /c/progs/kafka_2.11-1.0.0/bin/
export KAFKA_HOME=c:/progs/kafka_2.11-1.0.0/
./zookeeper-server-start.sh ../config/zookeeper.properties &>/d/k_z_logs/kafka-zookeeper.log
./kafka-server-start.sh ../config/server.properties &>/d/k_z_logs/kafka-server.log